name: test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: use node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: install modules
      run: npm install
    - name: run build
      run: npm run prod
    - name: run tests
      run: npm test
